global_costmap:
  global_frame: /odom
  robot_base_frame: base_stabilized
  update_frequency: 5.0
  publish_frequency: 2.0
  static_map: false
  rolling_window: true
  width: 24.0
  height: 24.0
  resolution: 0.05

