# # Definitions of tags to detect
#
# ## General remarks
#
# - All length in meters
# - Ellipsis (...) signifies that the previous element can be repeated multiple times.
#
# ## Standalone tag definitions
# ### Remarks
#
# - name is optional
#
# ### Syntax
#
# standalone_tags:
#   [
#     {id: ID, size: SIZE, name: NAME},
#     ...
#   ]
standalone_tags:
  [

  ]
# ## Tag bundle definitions
# ### Remarks
#
# - name is optional
# - x, y, z have default values of 0 thus they are optional
# - qw has default value of 1 and qx, qy, qz have default values of 0 thus they are optional
#
# ### Syntax
#
# tag_bundles:
#   [
#     {
#       name: 'CUSTOM_BUNDLE_NAME',
#       layout:
#         [
#           {id: ID, size: SIZE, x: X_POS, y: Y_POS, z: Z_POS, qw: QUAT_W_VAL, qx: QUAT_X_VAL, qy: QUAT_Y_VAL, qz: QUAT_Z_VAL},
#           ...
#         ]
#     },
#     ...
#   ]
tag_bundles:
  [
    {
      name: 'my_bundle',
      layout:
        [
          {id: 0, size: 0.05, x: 0.0000, y: 0.0000, z: 0.0000, qw: 1.0000, qx: 0.0000, qy: 0.0000, qz: 0.0000},
          {id: 4, size: 0.05, x: 0.0647, y: -0.0792, z: -0.0066, qw: 0.9971, qx: -0.0428, qy: 0.0621, qz: 0.0023},
          {id: 2, size: 0.05, x: 0.0641, y: 0.0851, z: -0.0089, qw: 0.9996, qx: 0.0138, qy: 0.0240, qz: -0.0022},
          {id: 1, size: 0.05, x: -0.0716, y: 0.0853, z: -0.0009, qw: 0.9994, qx: -0.0005, qy: -0.0336, qz: -0.0012},
          {id: 3, size: 0.05, x: -0.0697, y: -0.0781, z: 0.0059, qw: 0.9995, qx: 0.0326, qy: -0.0018, qz: -0.0023}
        ]
    }
  ]
